name: DeepSource Analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install DeepSource CLI
        run: curl https://deepsource.io/cli | sh

      - name: Run DeepSource analysis
        run: ./bin/deepsource analyze
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
